;; Windowed mode overrides
(when (display-graphic-p)
  (setq ring-bell-function 'ignore)
  (setq popup-menu-face "gray")
  (setq popup-menu-selection-face "gray12")
  (set-background-color "gray7")
  (set-foreground-color "white")
  (add-to-list 'default-frame-alist '(font .  "Source Code Pro"))
  (set-face-attribute 'default t :font "Source Code Pro")
  (setq mac-command-modifier 'meta)
  (set-face-attribute 'default (selected-frame) :height 105)
  (set-face-foreground 'font-lock-keyword-face  "OliveDrab1")
  (set-face-foreground 'popup-face  "white") (setq)
  (set-face-attribute 'font-lock-keyword-face nil :weight 'bold)
  (set-face-foreground 'font-lock-constant-face "blue1")
  (set-face-foreground 'font-lock-builtin-face "blue2")
  (tool-bar-mode -1)
  (set-face-attribute 'default (selected-frame) :height 105)
)
